name: Create production promotion pull request
on:
    # schedule:
    #     - cron: 0 18 * * 1
    workflow_dispatch:
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: production
      - name: Reset promotion branch
        run: |
          git fetch origin develop:develop
          git reset --hard develop

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge PR automatically"
          title: "Merge weather data updates"
          branch: data-updates/weather_data
          base: develop