name: Merge weather data updates
on:
    # schedule:
    #     - cron: 0 18 * * 1
    workflow_dispatch:
jobs:
  mergeWeatherUpdates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: test/develop
          lfs: True
          fetch-depth: 0

      - name: Pull LFS objects
        run: git lfs pull
  
          
      # - name: Reset data-updates/weather_data branch
      #   run: |
      #     git fetch origin develop:develop
      #     git reset --hard develop

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: data/weather_data/*.parquet
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge PR automatically"
          title: "Merge weather data updates"
          branch: test/weather_data
          base: test/develop
