name: Merge weather data updates
on:
    # schedule:
    #     - cron: 0 18 * * 1
    workflow_dispatch:
jobs:
  mergeWeatherUpdates:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: get_date
        run: echo "date=$(date +'%d-%m-%Y')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          ref: test/develop
          lfs: True
          fetch-depth: 0

      - name: Pull LFS objects
        run: git lfs pull

      # - name: Merge weather data updates
      #   uses: everlytic/branch-merge@1.1.5
      #   with:
      #     github_token: ${{ github.token }}
      #     source_ref: data-updates/weather-data
      #     target_branch: test/develop
      #     commit_message_template: '[Automated] Merged weather data updates - ${{ steps.get_date.outputs.date}}'

      - name: Merge weather data updates
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: data-updates/weather-data
          target_branch: test/develop
          message: '[Automated] Merged weather data updates - ${{ steps.get_date.outputs.date}}'
          github_token: ${{ github.token }}

    



