name: Merge weather data updates
on:
    schedule:
        - cron: 0 18 * * 1 # 9:00 every Monday
    workflow_dispatch:
jobs:
  mergeWeatherUpdates:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: get_date
        run: echo "date=$(date +'%d-%m-%Y')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          ref: develop
          lfs: True
          fetch-depth: 0

      - name: Pull LFS objects
        run: git lfs pull

      - name: Merge weather data updates
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          from_branch: data-updates/weather-data
          target_branch: develop
          github_token: ${{ github.token }}

    



