name: fetch past weather data

on:
  schedule:
    - cron: 0 2 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: get_date
        run: echo "date=$(date +'%d-%m-%Y')" >> $GITHUB_OUTPUT

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
        with:
          lfs: True

      - name: Pull LFS objects
        run: git lfs pull

      - name: Check LFS files are downloaded
        run: |
          ls data/weather_data
  

      # - name: setup python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.11.4' # install the python version needed


          
      # - name: install python packages
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
          
      # - name: execute py script
      #   run: |
      #     python src/data_fetch_scripts/fetch_weather_data.py

      # - name: Commit and Push results
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add .
      #     git commit -m "Data update ${{ steps.get_date.outputs.date}}"
      #     git push
