name: fetch past weather data

on:
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch:

env:
  MET_OFFICE_API_KEY: ${{ secrets.MET_OFFICE_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Get current date
        id: get_date
        run: echo "date=$(date +'%d-%m-%Y')" >> $GITHUB_OUTPUT

      - name: Checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
        with:
          lfs: True

      - name: Pull LFS objects
        run: git lfs pull

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.4' # install the python version needed
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute py script
        run: |
          python src/data_fetch_scripts/fetch_weather_data.py

      - name: Pull changes from remote branch
        run: git pull origin data_updates_weather_data

      - name: Commit and Push results to data_updates_weather_data branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Data update ${{ steps.get_date.outputs.date}}"
          git push origin HEAD:data_updates_weather_data
